account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'
urlpatterns = [
    # post views
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/',views.logout_view, name= 'logout'),
]

boardgames/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('',include('games.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.main, name='games'),
    path('<slug:game_slug>/', views.detail, name='detail'),
    path('add_comment/<slug:game_slug>/', views.add_comment, name='add_comment')
    # path('like/',views.likes_add, name='likes')
]

account/models.py
from django.db import models

# Create your models here.

games/models.py
import datetime

from django.contrib.auth.models import User

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from django.utils import timezone

rate_choices = [(0,0),(1,1),(2,2),(3,3),(4,4),(5,5)]
CAT_CHOICES = [('Cтратегия','Cтратегия'),('На двоих','На двоих'),('Экономическая','Экономическая'),('Кооперативная','Кооперативная'),('Вечеринка','Вечеринка')]

# Create your models here.


class Game(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(choices=CAT_CHOICES, max_length=255,default='Стратегия')
    # publisher = models.CharField(max_length=50)
    short_dscr = models.CharField(max_length=100,default='')
    description = models.CharField(max_length=700)
    img = models.ImageField(upload_to='images/',blank=True)
    img1 = models.ImageField(upload_to='images/',blank=True)
    img2 = models.ImageField(upload_to='images/',blank=True)
    img3 = models.ImageField(upload_to='images/',blank=True)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    rating = models.IntegerField(default=0, null=True, blank=True, choices=rate_choices)
    slug = models.SlugField(unique=True, db_index=True, verbose_name='URL')
    user_rate = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# class Vote(models.Model):
#     value = models.SmallIntegerField()
#     # user = models.ForeignKey(User, on_delete=models.CASCADE)
#     game = models.ForeignKey(Game, on_delete=models.CASCADE)
#     voted_on = models.DateTimeField(auto_now=True)
#
#     class Meta:
#         unique_together = ('user', 'game')


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=255, default='гость')
    post = models.ForeignKey(Game, on_delete=models.CASCADE, null=True, related_name='comment')
    pub_date = models.DateTimeField(default=timezone.now)
    text = models.TextField(default='')
    active = models.BooleanField(default=True)

account/forms.py
from django.contrib.auth.models import User
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

games/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import Textarea

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {'text': Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите ваш комментарий',
                'id': 'inputPassword5',
                'aria-describedby': 'passwordHelpBlock',
            }
        )}

account/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm,UserRegistrationForm
from django.contrib.auth import logout
from games import views as vgames


def logout_view(request):
    logout(request)
    return redirect(vgames.main)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(vgames.main)
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            #создание нового пользователя
            new_user = user_form.save(commit=False)
            #Сохранение пароля
            new_user.set_password(user_form.cleaned_data['password'])
            # Сохранение нового пользователя
            new_user.save()
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

games/views.py
from django.core.paginator import Paginator
from django.forms import model_to_dict
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from .models import Game, Comment
from .forms import CommentForm
from django.forms import model_to_dict
from django.http import JsonResponse
import json


def main(request):
    latest_games = Game.objects.order_by('-pub_date')
    paginator = Paginator(latest_games, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'games/main.html', context)


def detail(request, game_slug):
    game = get_object_or_404(Game, slug=game_slug)
    games_rec = Game.objects.filter(category=game.category)[:3]
    comment = game.comment.filter(active=True)
    form = CommentForm()
    context = {'game': game, 'form': form, 'comment': comment, 'rec': games_rec}
    return render(request, 'games/detail.html', context)

@require_POST
def add_comment(request, game_slug):
    game = get_object_or_404(Game, slug=game_slug)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.post = game
        new_comment.user = request.user
        new_comment.save()
        return JsonResponse(
            {"text": new_comment.text, 'user': new_comment.user.username}, status=201)
    else:
        return JsonResponse(form.errors.as_data(), safe=False, status=200)



# def likes_add(request):

games/templates/games/detail.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}

{% if user.is_authenticated %}
    {% include "games/navbar_login.html"%}
{% else %}
    {% include "games/navbar.html"%}
{% endif %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/detail.css' %}">
    {% endblock %}
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script>

        $(function(){
            $('#form').on('submit', function(){
                $.ajaxSetup({data: {csrfmiddlewaretoken: '{{ csrf_token }}'}});
                $.ajax({
                url: '{% url 'add_comment' game_slug=game.slug %}',
                data: $('#form').serialize(),
                method: 'post',
                success: function(data){
                    console.log(data);
                    $('#comments-list').append('<div class="comments">' + '<p>' + '<font size="5" color="#fa8e47" face="sans-serif">' + '<b>' + data.user + '</b>' + '</font>' + '</p>' + '<p>' + '<font face="sans-serif">'+ data.text + '</font>' + '</p>' + '</div>')
                     $('#form').trigger('reset');
                }

            });

                return false;
            });
        });

    </script>
</head>
<body>
<div class="wrapper">
{% if game %}
<div class="game-detail">
    <h1><font size="10" color="#fa8e47" face="sans-serif">{{ game.title }}</font></h1>
    <img src="{{game.img.url}}" class="card-img-top" alt="...">
    <div class="dscr"><p>{{ game.description }}</p></div>
</div>
{% endif %}
    {% if rec %}
<div class="recomends">
    <h2>Также рекомендую к просмотру:</h2>
    {% for game_rec in rec %}
        {% if game_rec.slug != game.slug %}
    <div class="single-rec">
    <a href="{% url 'detail' game_rec.slug %}">
    <p>{{ game_rec.title }}</p>
    <img src="{{game_rec.img.url}}" class="img-rec" alt="...">
        </a>
        </div>
        {% endif %}
    {% endfor %}
</div>
    {% endif %}
</div>
<div id="comments-list">
    {% if comment %}
        {% for com in comment %}
        <div class="comments">
            <p><font size="5" color="#fa8e47" face="sans-serif"><b>{{ com.user }}</b></font></p>
            <p><font face="sans-serif">{{ com.text }}</font></p>
        </div>
        {% endfor %}
    {% endif %}
</div>

{% if user.is_authenticated %}

    <form id="form" action="." method="post">
        {% csrf_token %}
        <label for="inputPassword5" class="form-label">Ваш комментарий</label>
                {{ form.text }}
        <div id="passwordHelpBlock" class="form-text">
            Ваше мнение о данном посте)
        </div>
        <button type="submit" class="btn btn-outline-info btn-lg">Отправить</button>
        </form>
{% else %}
<div class="not-auth">
<p><font size="5" face="sans-serif">Авторизируйтесь для добавления комментариев.</font></p>
    </div>
{% endif %}

</div>
</body>
</html>

games/templates/games/main.html
<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}

 {% if user.is_authenticated %}
    {% include "games/navbar_login.html"%}
{% else %}
    {% include "games/navbar.html"%}
{% endif %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/navbar.css' %}">
    <meta charset="UTF-8">
</head>
<body>
{% if page_obj %}
    {% for game in page_obj %}

        <div class="card mb-3">
            <a href="{% url 'detail' game.slug %}">
          <img src="{{game.img.url}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ game.title }}</h5>
            <p class="card-text">{{ game.short_dscr }}</p>
            <p class="card-text"><small class="text-muted">Опубликовано: {{ game.pub_date }}<br>


                {% if game.rating == 5  %}
                    Моя оценка: 💗💗💗💗💗
                {% elif game.rating == 4 %}
                    Моя оценка: 💗💗💗💗🤍
                {% elif game.rating == 3 %}
                    Моя оценка: 💗💗💗🤍🤍
                {% elif game.rating == 2 %}
                    Моя оценка: 💗💗🤍🤍🤍
                {% elif game.rating == 1 %}
                    Моя оценка: 💗🤍🤍🤍🤍
                {% elif game.rating == 0 %}
                    Моя оценка: 🤍🤍🤍🤍🤍
                {% endif %}
            </small></p>
                    <p class="card-text">{{ game.com }}</p>

          </div>
              </a>


        </div>

    {% endfor %}
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
<!--            <a href="?page=1">&laquo; first</a>      -->
            <a id='btn-first-page'class="btn btn-outline-info btn-pag" href="?page=1" role="button"><font size="4" face="sans-serif">&laquo;</font></a>
            <a id='btn-prev-page'class="btn btn-outline-info btn-pag" href="?page={{ page_obj.previous_page_number }}" role="button"><font size="4" face="sans-serif">&lsaquo;</font></a>

        {% endif %}

        <span class="current">
            <font size="4" face="sans-serif">Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</font>
        </span>

        {% if page_obj.has_next %}
            <a id='btn-next-page'class="btn btn-outline-info btn-pag" href="?page={{ page_obj.next_page_number }}" role="button"><font size="4" face="sans-serif">&rsaquo;</font></a>
            <a id='btn-last-page'class="btn btn-outline-info btn-pag" href="?page={{ page_obj.paginator.num_pages }}" role="button"><font size="4" face="sans-serif">&raquo;</font></a>
        {% endif %}
    </span>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

games/templates/games/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Блог</title>{% endblock %}
    {% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/navbar.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'games' %}"><font size="6" face="sans-serif">SerGamesBlog</font></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!--    <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--      <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Link</a>-->
<!--        </li>-->
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled">Disabled</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <form class="d-flex" style="margin-left: 55vw;" >-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
      {% block user %}
      <a id='btn-login'class="btn btn-outline-info btn-lg" href="{% url 'account:login' %}" role="button"><font size="5" face="sans-serif">Войти</font></a>
      <a id='btn-reg'class="btn btn-outline-info btn-lg" href="{% url 'account:register' %}" role="button"><font size="5" face="sans-serif">Регистрация</font></a>
      {% endblock %}
    </div>
  </div>
</nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

games/templates/games/navbar_login.html
{% extends 'games/navbar.html' %}

{% block user %}
{% if user %}

                <h3>{{ user.username }}</h3>
          {% endif %}
          <a id="btn-exit" class="btn btn-outline-info btn-lg" href="{% url 'account:logout' %}" role="button"><font size="5" face="sans-serif">Выход</font></a>
{% endblock %}

games/templates/games/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>